# Generated by Django 2.2.6 on 2019-11-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('impressions', models.IntegerField(blank=True)),
                ('clicks', models.IntegerField(blank=True)),
                ('installs', models.IntegerField(blank=True)),
                ('spend', models.IntegerField(blank=True)),
                ('revenue', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'metric',
            },
        ),
    ]
